name: Android CI/CD & Auto Release 🚀

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build & Release Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 📂
        uses: actions/checkout@v4

      - name: Set up JDK 17 ☕
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew 🔑
        run: chmod +x gradlew

      # بازگرداندن فایل Keystore از Base64
      - name: Decode Keystore 🔐
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/keystore.jks

      # کامپایل و امضای خودکار
      - name: Build Release APK & Bundle 🛠️
        run: ./gradlew assembleRelease bundleRelease --stacktrace
        env:
          STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # ایجاد ریلیز در گیت‌هاب
      - name: Create GitHub Release 📦
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
